name = "fedoraImage"
description = "My custom Fedora image for running containers"
version = "1.0.0"

[[packages]]
name = neofetch

[[packages]]
name = neovim

[[packages]]
name = git

[[customizations.user]]
 name = "root"
 description = "root user"
 password = "$6$oLXrRC0P8BzCHztb$L1yr5FOV2YabQf03LZlCIjw.9xGQNdPf/NT2NVeQSzpJ5pm/WL4ZUVFqaa7FrXMagWuCT49QP3m5U3e7HGXyx/"
 home = "/home/root/"
 shell = "/usr/bin/bash"
 groups = ["root"]
